export { default as Home } from './Home'
export { default as Pizza } from './Pizza'
export { default as Details } from './Details'
export { default as Cart } from './Cart'
export { default as NotFound } from './NotFound'
